inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

# We seldom check the return value of 'update' to see if
# the operation was successful. Since we assume success, we
# should raise an exception if this is not the case.
#
# We intend to add this to rubocop-govuk.
Rails/SaveBang:
  Enabled: true
